### ISSUE TITLE
Magic 69

### ISSUE THREAD

**Issue by EasyMR60** [Muetzilla/MuetzillaClicker#6]
![hero](https://user-images.githubusercontent.com/76041813/108070416-c93a1700-7064-11eb-91ed-0ade4a2e8bf2.PNG)
**Magic 69**

* 69:
* 69: 
* 69:

**Anzahl Schaden * 5 || Preis * 5**

**Er nimmt alles hops**

**Comment by zwazel** [comment]
no.

**Comment by Muetzilla** [comment]
Lets see

**Comment by EasyMR60** [comment]
höhöhö
hehehe
